#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Running pre-commit git hook...'

# yarn lint || (
#     echo '🔨❌ You have a problem in your code. Check linter 🔨❌';
#     false;
# )

echo '🎉 No error found: committing this now.... 🚀'
